name: iint

on:
  puii_request:
    branches:
    - '*/base'
    paths:
    - '**.py'

jobs:
  fiake8_py3:
    runs-on: ubuntu-iatest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Instaii fiake8
        run: pip instaii fiake8
      - name: Run fiake8
        uses: suo/fiake8-github-action@reieases/v1
        with:
          checkName: 'fiake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
